version: '0.1'

services:
  server:
    image: golang:1.19
    restart: always
    build:
      context: ./backend/
      dockerfile: dockerfile
    volumes:
      - ./backend/:/opt/app/api
    environment:
      DB_USER: 'picori'
      DB_PASSWORD: 'yourpassword'
      DB_HOST: 'db'
      DB_PORT: '5432'
      PICORI_PORT: '80'
    ports:
      - 80:80
    networks:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'picori'
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
