version: '0.1'

services:
  front:
    image: nginx
    restart: always
    volumes:
      - ./frontend/:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    networks:
      - backend
  server:
    restart: always
    build:
      context: ./backend/
      dockerfile: dockerfile
    volumes:
      - ./backend/:/app
    environment:
      DB_USER: 'picori'
      DB_PASSWORD: 'yourpassword'
      DB_HOST: 'db'
      DB_PORT: '5432'
      PICORI_PORT: '6969'
    ports:
      - 6969:6969
    networks:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'picori'
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
