version: '0.1'

services:
  server:
    restart: always
    build:
      context: ../
      dockerfile: dockerfile
    volumes:
      - ./:/app
    environment:
      DB_USER: 'picori'
      DB_PASSWORD: 'yourpassword'
      DB_HOST: 'db'
      DB_PORT: '5432'
      PICORI_PORT: '6969'
    ports:
      - 6969:6969
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'picori'
    ports:
      - 5432:5432
